[package]
name = "kv_store"
version = "0.1.0"
edition = "2024"

[dependencies]
libc          = "0.2.175"
thiserror     = "2.0.0"
core_affinity = "0.8.3"

[profile.dev]
warnings = false

[profile.release]
warnings = true
