[package]
name = "kv_store"
version = "0.1.0"
edition = "2024"

[dependencies]
core_affinity = "0.8.3"

[target.'cfg(not(windows))'.dependencies]
libc = "0.2.175"

[profile.dev]
warnings = false

[profile.release]
warnings = true
